### ISSUE TITLE
How to see reports ?

### ISSUE THREAD

**Issue by kirantpatil** [thinreports/thinreports-rails5-example#3]
I followed your steps.

created tasks and it displays them when I hit url "localhost:3000/tasks"

I don't see any reports, so how do I see one ?

Thanks.

**Comment by stevensona** [comment]
@kirantpatil look at the [index action in TasksController](https://github.com/thinreports/thinreports-rails5-example/blob/master/app/controllers/tasks_controller.rb#L11). To view the report, visit http://localhost:3000/tasks.pdf

**Comment by hidakatsuya** [comment]
I added a print button on the list page and detail page. See b287759071e97b1030db50db5730b059668bf307 and 70bedd2d59fb5c8f9a2cc132eee4099e034a7117 .

**Comment by hidakatsuya** [comment]
There is no reaction for a while. Close this issue.
